### ISSUE TITLE
Making the website more responsive and footer appealing 

### ISSUE THREAD

**Issue by Ayushswirlon** [Rachit4039/FoodDsy#21]
The website is overall not responsive due smaller device
The goal is to make the website more responsive for smaller device
Also will work on footer to make it more appealing.

**Comment by kratik1237** [comment]
he is not responding since 3 weeks can i do that

**Comment by kratik1237** [comment]
@Rachit4039

**Comment by Ayushswirlon** [comment]
Yes plz I will not be able to do that

**Comment by Rachit4039** [comment]
fine
