### ISSUE TITLE
Improving the About Page

### ISSUE THREAD

**Issue by shravn-10** [Rachit4039/FoodDsy#3]

**Comment by shravn-10** [comment]
Hi rachit i noticed that u assigned an issue regarding the about page to someone else, and gave the tag hard .
can i ask why mine is easy 
and pls do not assign the same issues to multiple people at the same time cause that causes a lot of confusion.

**Comment by Rachit4039** [comment]
Please make it responsive

**Comment by shravn-10** [comment]
Ok will do

**Comment by shravn-10** [comment]
please assign me 20 points since issue 1 and 2 have been closed
PR 16 addressed both
