### ISSUE TITLE
Greet People on Creating Issues/PR

### ISSUE THREAD

**Issue by deepesh611** [Rachit4039/FoodDsy#42]

**Comment by Rachit4039** [comment]
what is the issue?

**Comment by deepesh611** [comment]
The contributors are greeted when they raise an issue or create a PR. 

something like auto commenting

**Comment by Rachit4039** [comment]
what are your plans for this ?

**Comment by deepesh611** [comment]
well, it is just a good idea to thank people for raising an issue or submitting a PR, since it helps your project to grow.

for this to work, we have to create a file or two, to automate the greeting process.

**Comment by deepesh611** [comment]
so what do you think @Rachit4039 ?

**Comment by Rachit4039** [comment]
can you do it by today ?

**Comment by deepesh611** [comment]
> can you do it by today ?

yep, can do

**Comment by deepesh611** [comment]
@Rachit4039, I have created a PR, pls have a look
#47 


pls make sure to update the score

**Comment by Rachit4039** [comment]
done
